# This example has you passing the environment variables manually 
# During the run process and is less recommended

FROM alpine:latest

# Install dependencies and awscli 

RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*

COPY aws_env.sh /aws_env.sh
CMD tail -f /dev/null
ENTRYPOINT ["/bin/sh" , "-c", "source /aws_env.sh && printenv"]





